import Profile from "@/components/profile/Profile";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Eventure - Profile",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Profile />
    </div>
  );
};

export default page;
